#!/bin/bash

# Unload the macOS WindowManager process
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist >/dev/null 2>&1 &

# Load scripting additions
sudo yabai --load-sa

#Setup basic signals
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_created action="sketchybar --trigger space_windows_change"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger space_windows_change"

# Float small, non-resizable windows
yabai -m signal --add event=window_created action='yabai -m query --windows --window $YABAI_WINDOW_ID | jq -er ".\"can-resize\" or .\"is-floating\"" || yabai -m window $YABAI_WINDOW_ID --toggle float'

# Make yabai window manager aware of sketchybar
yabai -m config external_bar all:40:0

yabai_config=(
  window_placement          second_child
  focus_follows_mouse       autoraise
  mouse_modifier            fn
  menubar_opacity           0.0
  window_animation_duration 0.0
  layout                    bsp
  auto_balance              off
  top_padding               0
  bottom_padding            8
  left_padding              8
  right_padding             8
  window_gap                8
)

yabai -m config ${yabai_config[*]}

# Setup spaces
function setup_space {
  local idx="$1"
  local name="$2"
  local space=
  echo "setup space $idx : $name"

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space --create
  fi

  yabai -m space "$idx" --label "$name"
  echo yabai -m space "$idx" --label "$name"
}

setup_space 1 Terminal
setup_space 2 Daily
setup_space 3 Slack
setup_space 4 Colab
setup_space 5 Code
setup_space 6 Android
setup_space 7 Spotify


# Assign apps to specific spaces
yabai -m rule --add app="^(iTerm)$" space=^1
yabai -m rule --add app="^(Calendar | Mail | Jira | Chrome | Github | Notion)$" space=^2
yabai -m rule --add app="^(Slack)$" space=^3
yabai -m rule --add app="^(Chrome)$" space=^4
yabai -m rule --add app="^(Code)$" space=^5
yabai -m rule --add app="^(Android Studio)$" space=^6
yabai -m rule --add app="^(Spotify)$" space=^7

# https://github.com/koekeishiya/yabai/issues/2170
# yabai -m rule --add app=".*" sub-layer=normal

# Manage apps and windows
yabai -m rule --add app="^(Raycast|Calculator|Software Update|Dictionary|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|App Store|Clock|Installer|Activity Monitor|Finder)$" manage=off
yabai -m rule --add label="Small windows" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Android Commit" app="Android Studio" title="Commit Changes" manage=off
yabai -m rule --add app="Slack" title="Huddle with" manage=off
yabai -m rule --add app="Android Studio" title="Create New Branch" manage=off
yabai -m rule --add app="Android Studio" title="Add File to Git" manage=off
yabai -m rule --add app="Android Studio" title="Conflicts" manage=off
yabai -m rule --add app="Android Studio" title="Merge Revisions for" manage=off
yabai -m rule --add app="Android Studio" title="Rename" manage=off
yabai -m rule --add app="Android Studio" title="Delete" manage=off
yabai -m rule --add app="Android Studio" title="Uses Detected" manage=off
yabai -m rule --add app="Android Studio" title="Push Commits" manage=off
yabai -m rule --add app="Android Studio" title="Choose Process" manage=off
yabai -m rule --add label="Mail New Message" app="^Mail$" title="(New Message)" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add app="^IINA$" sticky=on manage=off

# Apply rules to existing windows
yabai -m rule --apply

echo "Yabai configuration loaded…"
